---
- name: Instalar Docker en nodos de aplicación
  hosts: api,core,monitoring
  become: true

  tasks:
    - name: Instalar dependencias
      apt:
        name:
          - docker.io
        state: present
        update_cache: yes

    - name: Habilitar Docker
      service:
        name: docker
        enabled: yes
        state: started
